### ISSUE TITLE
Post image as the link

### ISSUE THREAD

**Issue by Ruriko** [raspi/SimpleRedditRSSBot#3]
Is it possible to make it submit image url from RSS as the link on reddit?

**Comment by raspi** [comment]
Bot simply submits whatever is on the `link` tag on the feed. So yes. Or did you mean something else?

**Comment by Ruriko** [comment]
No that is not what I want. The RSS I want to use contains embedded images I want the bot to submit the image url in <img> instead of the link tag. Example RSS http://pix.adoreanime.com/pixiv/search/vocaloid/other/safe (contains large images)
